// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsqmRbFAlwLlijjbGtrQP8aPzvwLD7uwo',
    appId: '1:774143835896:web:c554ecaa89bd5aa26f850d',
    messagingSenderId: '774143835896',
    projectId: 'dompetku-1e1a4',
    authDomain: 'dompetku-1e1a4.firebaseapp.com',
    storageBucket: 'dompetku-1e1a4.firebasestorage.app',
    measurementId: 'G-DYK96XTQ21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBetm7TN-pxq-ctNHipYOAohWbWwleo2g0',
    appId: '1:774143835896:android:b68a59c1b85c5cd86f850d',
    messagingSenderId: '774143835896',
    projectId: 'dompetku-1e1a4',
    storageBucket: 'dompetku-1e1a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUyXROLCMjz3AW6ATV2lC6AnKgs8RJrx8',
    appId: '1:774143835896:ios:54d6cf19d5f5ed1f6f850d',
    messagingSenderId: '774143835896',
    projectId: 'dompetku-1e1a4',
    storageBucket: 'dompetku-1e1a4.firebasestorage.app',
    iosBundleId: 'com.example.moneymanagetest',
  );
}
